### ISSUE TITLE
Game starts to stutter after the plugin has been on for a while

### ISSUE THREAD

**Issue by MtxGrav** [digital-pet/AetherSenseRedux#6] opened 2021-12-18 20:40 UTC
After about half an hour of having the plugin up and using it, I started encountering an increasing amount of lag-related issues, symptoms include:
-  Chat messages seem to come in a few seconds after the plugin responds to them,
- Enemies and NPC's freeze on-screen, 
- My character wouldn't stop using its sprint animation even while completely stationary 
-  Fate complete message didn't pop up 

I don't have an exact reproduciton path for this, but I was adding triggers, modifying them, applying and saving them, and just generally setting up and using the plugin without doing anything in particular.

I had this issue about a week ago too and didnt use it after that until today. I reinstalled it before today's use

**Comment by digital-pet** [comment] 2021-12-18 23:38
Thanks for the report. I'll see if I can reproduce this on my end. If you can determine any more specific steps for reproducing this, please let me know!

**Comment by digital-pet** [comment] 2021-12-18 23:46
If you encounter this again, could you check the CPU usage of ffxiv_dx11.exe and IntifaceCLI.exe in Task Manager?  I suspect this may be related to an issue I've observed in IntifaceCLI on windows which causes it to use progressively more CPU on all cores.

**Comment by MtxGrav** [comment] 2021-12-21 11:48
I played around with it some more, and I didn't have any issues this time. If/when it happens again, i'll be sure to let you know, with the information you asked for.

**Comment by digital-pet** [comment] 2021-12-22 06:42
If you haven't seen on the discord yet I released a new beta version v0.6.211221, this fixes several issues that could have potentially caused memory leaks in situations where the plugin was being disconnected and reconnected repeatedly. It'll be uploaded here tomorrow.

**Comment by digital-pet** [comment] 2022-01-02 05:00
I went ahead and marked this as "can't reproduce" - if you encounter this issue again in the future feel free to reopen the issue.

**Closed as completed by digital-pet** 2022-01-02 05:00 UTC
Labels: can't reproduce
